thinktank/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    student_register,
    student_login,
    logout_view,
    faculty_register,
    faculty_login,
    profile,
    change_password_view,
    StudentUpdate,
    DashboardView,
    FacultyUpdateView,
    FacultyListView,
    StudentListView,
)

app_name = "accounts"

urlpatterns = [
    url(r'^profile/(?P<username>[\w.@+-]+)$', profile, name='profile'),
    url(r'^student/register/$', student_register, name="stud_register"),
    url(r'^faculty/register/$', faculty_register, name="faculty_register"),
    url(r'^faculties/$', FacultyListView.as_view(), name="faculty_list"),
    url(r'^students/$', StudentListView.as_view(), name="student_list"),
    url(r'^(?P<username>[\w.@+-]+)/dashboard/$',
        DashboardView.as_view(),
        name='dashboard'),
    url(r'^student/login/$', student_login, name='stud_login'),
    url(r'^faculty/login/$', faculty_login, name='faculty_login'),
    url(r'^student/(?P<username>[\w.@+-]+)/edit/$',
        StudentUpdate.as_view(),
        name='stud_update_profile'),
    url(r'^faculty/(?P<username>[\w.@+-]+)/edit/$',
        FacultyUpdateView.as_view(),
        name='faculty_update_profile'),
    url(r'^change_password/$', change_password_view, name='change_password'),
    url(r'^logout/$', logout_view, name='logout'),
]

thinktank/blogs/urls.py
from django.conf.urls import url
from .views import (
    BlogListView,
    BlogDetailView,
    CreateBlogView,
    BlogDeleteView,
    BlogUpdateView,
)

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog_list'),
    url(r'^(?P<pk>\d+)$', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    url(r'^new/$', CreateBlogView.as_view(), name='create_blog'),
    url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
        name='blog_delete'),
]

thinktank/events/urls.py
from django.conf.urls import url
from .views import (EventList, EventDetail, EventDelete,
                    event_post_view, event_update_view, delete_photo_of_event,
                    add_photo_on_event, add_video_on_event, delete_video_of_event)

app_name = 'events'

urlpatterns = [
    url(r'^new/$', event_post_view, name='post_event'),
    url(r'^$', EventList.as_view(), name='event_list'),
    url(r'(?P<pk>\d+)/$', EventDetail.as_view(), name='event_detail'),
    url(r'(?P<pk>\d+)/delete/$', EventDelete.as_view(), name='event_delete'),
    url(r'(?P<pk>\d+)/edit/$', event_update_view, name='event_edit'),
    url(r'(?P<pk>\d+)/photo/add/$',
        add_photo_on_event, name='add_photo'),
    url(r'(?P<pk>\d+)/video/add/$',
        add_video_on_event, name='add_video'),
    url(r'(?P<pk>\d+)/photo/(?P<pk1>\d+)/delete$',
        delete_photo_of_event, name='delete_photo'),
    url(r'(?P<pk>\d+)/video/(?P<pk1>\d+)/delete$',
        delete_video_of_event, name='delete_video'),
]

thinktank/homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = "homepage"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

thinktank/homepage/models.py
from django.db import models

# Create your models here.

thinktank/homepage/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class ContactUsForm(forms.Form):
    from_email = forms.EmailField(label='Email', max_length=50, widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    subject = forms.CharField(label='Subject', max_length=100, help_text='100 characters max.', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    detail = forms.CharField(label='Detail', widget=forms.Textarea(
        attrs={'class': 'form-control'}))

thinktank/homepage/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from accounts.forms import UserLoginForm
from .forms import ContactUsForm
from django.contrib.auth import login
from django.core.mail import send_mail
from events.models import Event
import datetime


def index(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user_obj = form.cleaned_data.get('user_obj')
            login(request, user_obj)
            return HttpResponseRedirect("/account/profile/{0}".format(
                user_obj.username))
    else:
        form = UserLoginForm()
    upcoming_events = Event.objects.filter(
        when_date__gte=datetime.datetime.now().date()).order_by('when_date', 'when_time')
    return render(request, 'homepage/index.html', {'form': form, 'upcoming_events': upcoming_events})


def about(request):
    return render(request, 'homepage/about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['detail']
            from_email = form.cleaned_data['from_email']
            msg = from_email + " sent feedback: " + message
            send_mail(
                subject,
                msg,
                from_email,
                ["konaseemathinktank2019@gmail.com", "g_jena@rediffmail.com", ],
                fail_silently=False,
            )
            return HttpResponseRedirect('/thanks/')
    else:
        form = ContactUsForm()

    return render(request, 'homepage/contact.html', {'form': form})

thinktank/templates/homepage/_footer.html
<div class="footer">
    <div class="container">
        <div style="float:left;width: 50%">
            <p>&copy; Copyright 2018. All Right Reserved.</p>
        </div>
        <div style="float:left;width: 50%">
            <p style="float:right">Developed by: <a href="https://github.com/Rupyes" target="blank">Rupesh
                    Maharjan</a> </p>
        </div>
    </div>

</div>

thinktank/templates/homepage/_head.html
<div class="container">
    <img align="left" src="/media/images/logo/bvc.jpeg" width="120px" height="150px" />
    <img src="/media/images/logo/jntuk.png" width="150px" height="150px" align="right" />
    <div style="width:80%;">
        <h2 style="text-align: center; color: #000;">Konaseema Think Tank</h2>
        <h5 style="text-align: center; color: #000;">Developed by: BVC Engineering College (Autonomous)<br>
            East Godavari, Andra Pradesh 533210 <br> Accredited by: NBA, NAAC and Approved by: AICTE (New Delhi)
        </h5>
    </div>
</div>

thinktank/templates/homepage/_navbar.html
<div class="menu">
    <hr style="background: #000;">
    <div class="container">
        <nav class="nav nav-pills nav-fill">
            <a class="nav-item nav-link" href="{% url 'homepage:index'%}">Home</a>
            <a class="nav-item nav-link" href="{% url 'homepage:about' %}">About</a>
            <a class="nav-item nav-link" href="#">Guest</a>
            <a class="nav-item nav-link" href="{% url 'accounts:faculty_list'%}">Faculty</a>
            <a class="nav-item nav-link" href="{% url 'accounts:student_list'%}">Students</a>
            <a class="nav-item nav-link" href="#">Critics</a>
            <a class="nav-item nav-link" href="{% url 'events:event_list' %}">Events</a>
            <a class="nav-item nav-link" href="{% url 'homepage:contact' %}">Contact</a>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {% if request.user.is_faculty %}
                    {% if  request.user.faculty.profile_picture %}
                    <img src="{{ request.user.faculty.profile_picture.url }}" alt="picture" class="rounded-circle"
                        width="50" />
                    {%endif%}
                    {% if not request.user.faculty.profile_picture %}
                    <img src="/media/icons/person_icon.png" style="background:#ddd;" class="rounded-circle"
                        alt="picture" width="50" />
                    {%endif%}
                    {% endif %}
                    {% if request.user.is_student %}
                    {% if  request.user.student.profile_picture %}
                    <img src="{{ request.user.student.profile_picture.url }}" alt="picture" class="rounded-circle"
                        width="50" />
                    {%endif%}
                    {% if not request.user.student.profile_picture %}
                    <img src="/media/icons/person_icon.png" style="background:#ddd;" class="rounded-circle"
                        alt="picture" width="50" />
                    {%endif%}
                    {% endif %}
                    {{request.user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.is_faculty%}
                    <a class="dropdown-item"
                        href="{% url 'accounts:profile' username=request.user.username %}">Profile</a>
                    <a class="dropdown-item"
                        href="{% url 'accounts:dashboard' username=request.user.username %}">Dashboard</a>
                    {%endif%}
                    {% if request.user.is_student%}
                    <a class="dropdown-item"
                        href="{% url 'accounts:profile' username=request.user.username %}">Profile</a>
                    {%endif%}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:logout'%}">Log Out</a>
                </div>
            </li>
            {% endif %}

        </nav>
    </div>
    <hr style="background: #000;">
</div>

thinktank/templates/homepage/about.html
{% extends 'thinktank/base.html' %}

{% block title %}About{% endblock%}

{% block content %}

<h4>About BVCEC</h4>
<hr>
<p>
    Late Bonam Venkata Chalamayya, A visionary, who understood that the success of the country, its wealth and welfare,
    will depend on the nation’s assets such as ideas and skills of its population. The world is becoming increasingly
    technological and the value of national assets will be determined by the effectiveness of science, technology,
    engineering and mathematics education. That gave birth to BVC educational society in 1992 and emergence of the first
    private engineering college, BONAM VENKATA CHALAMAYYA ENGINEERING COLLEGE, ODALAREVU, East Godavari district, Andhra
    Pradesh in 1997.

    Despite innumerable difficulties and insurmountable obstacles he had faced, he didn’t budge from his firm
    determination to realize his vision and accomplish success while making significant contribution towards development
    of country in building assets.

    Sri Bonam Venkata Chalamayya is a great personality who made a humble beginning as a peasant rose to be an
    industrialist, philanthropist and stands as an inspiration today to the country.

    BVC group, as India’s leading next-generation institutions – living,growing and youthful, that embrace change and
    opportunity with a can-do attitude. BVC group is located in the nation’s second richest district EAST GODAVARI of
    Andhra Pradesh.The BVC group inspires and supports discovery, creativity and innovation across all disciplines. The
    BVC group attracts and nurtures the talent that drives new knowledge creation, improves lives and betters our world.
    In this rich learning environment, the group serves thousands of students in shaping their career towards success,
    and provides the community with diverse lifelong learning opportunities. International best practices, volunteer
    work, and research programs, industry – interaction programs, cross culture environment give students a global
    context while promoting diversity and innovation in teaching and research.

    Our focus is not just education but we actively engage students in leadership development in all areas—the arts,
    athletics, science, engineering, volunteerism and business. We are also a leader in sustainability – living a set of
    values embraced by the campus through teaching, leadership, and campus operations.

    BVC is a place, which provides exploratory time for students to discover their passions, ideas and values with the
    help of best quality faculty and peers. We ensure to provide individual and social benefit by providing a chance to
    focus on learning, spread one’s intellectual wings and test one’s limits. Thus, at BVC group, we foster
    intellectual, social, ethical and civic development, which is essential to evolve to be a capable and responsible
    individual.

</p>
<p>

    VISION <br>

    To become a leading technical institute of academic excellence by imparting high patterns of discipline through
    innovative programs of global standards making our students technologically superior and ethically strong to serve
    the Nation.
</p>
<p>
    MISSION
    <br>
    To create an environment that shall foster the growth of intellectually capable, innovative professionals who can
    contribute to the growth of technology in partnership with industry and develop and harness it for the welfare of
    Nation and mankind.
</p>
<p>

    QUALITY POLICY
    <br>
    BVCEC strives to establish a system of quality assurance to continuously address, monitor and evaluate the quality
    of education offered to students thus promoting effective teaching–learning processes to enhance student’s skills
    and talents for their exemplary contribution to the society, the Nation and the World.
</p>

<ul>
    <p>
        Goals <br>
        Short term goals :</p>
    <li> To have state-of – the –art infrastructure for laboratories , student centric activities and building and
        amenities</li>

    <li> To achieve academic excellence by getting 90-100 percentage passing in university examinations

    <li> To help students to foster and develop qualities of leadership interpersonal and problem solving skills to face
        the professional and personal challenges in the life

    <li> To inculcate qualities of integrity, honesty , loyalty and patriotism among the students

    <li> To have good record of reputed companies visiting and offering jobs for our students at our campus and achieve
        50% placement

    <li> To enable scholarly vibrant environment for learning , teaching , research and development for student and
        staff for their personal and professional growth

    <li> To faster and harmonious and cardinal relationship among the management , faculty and staff and students for
        their respective growth and for establishing to congener academic environment in the college.
</ul>
<ul>
    <p>
        Long term goals:</p>
    <li>To become the preferred college of choice for students who do well in EAMCET and be listed among top ten
        colleges in
        A.P.

    <li></li>To reach a level of expertise where faculty from college are taking up major consulting assignments in the
    wide
    range of technical areas

    <li></li>To achieve 100% results and 100% placements consistently

    <li></li>To evolve as center for excellence by undertaking nationally and internationally acknowledged research and
    development works

    <li></li>To evolve as autonomous and deemed institution
</ul>

{% endblock%}

thinktank/templates/homepage/contact.html
{% extends 'thinktank/base.html' %}

{% block title %}About{% endblock%}

{% block content %}

<h4>Contact Us</h4>
<hr>
<p>
    BVC Engineering College (Autonomous) <br>
    Odalarevu, 533210 <br>
    Amalapuram <br>
    Andra Pradesh, India
</p>
<hr>
<h4>Feedback</h4>
<hr>
<form action="" method="POST">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Send" class="btn btn-primary">
</form>




{% endblock%}

thinktank/templates/homepage/index.html
{% extends 'thinktank/base.html' %}

{% block title %}HomePage{% endblock%}

{% block content %}
{% if not user.is_authenticated%}
<div class="login_faculty">

    <h4>Login!!</h4>
    <form method="post" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="Login" />
        <p>
            New User? Register for:
            <a href="{% url 'accounts:stud_register' %}">Student</a> or
            <a href="{% url 'accounts:faculty_register' %}">Faculty</a>.
        </p>
        <p>
            OR, <a href="{% url 'reset_password'%}">Forgot password?</a>
        </p>
    </form>

</div>

<div class="desc">
    <p style="margin-left: 5px; font-size: 18px; ">
        <b>Welcome</b> to the Konaseema Think Tank. The purpose of this website is to bring all intellectuals on
        one platform and provide them a forum for innovation, creativity and sharing intellectual
        solutions and services to the researchers, student community and citizens.
    </p>
</div>
{% endif%}
{% if user.is_authenticated%}

<div class="desc" style="float:left; width: 100%;">
    <h4>Hi! {{ request.user.first_name}}</h4>
    <hr>
    <p style="margin-left: 5px; font-size: 18px; ">
        <b>Welcome</b> to the Konaseema Think Tank. The purpose of this website is to bring all intellectuals on
        one platform and provide them a forum for innovation, creativity and sharing intellectual
        solutions and services to the researchers, student community and citizens.
    </p>
</div>
{% endif %}
<div style="float:left; width: 100% ;margin-top:20px;">

    <h4>Upcoming Events</h4>
    <hr>
    {% for event in upcoming_events %}
    <div class="card" style="width: 100%; float: left; margin-left:5px; margin-bottom: 5px;">
        <div class="card-body">
            <h5 class="card-title">{{ event.title}}</h5>
            <hr>
            <p class="card-text">{{event.description|truncatewords:'10'}}</p>
            <p style="font-size: 12px;">on {{event.when_date}} at {{event.venue}}</p>
            <a href="{% url 'events:event_detail' pk=event.pk%}" class="btn btn-primary">Detail</a>
        </div>
    </div>
    {% empty %}
    <p>No upcoming events.</p>
    {% endfor%}

</div>

{% endblock%}