thinktank/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    student_register,
    student_login,
    logout_view,
    faculty_register,
    faculty_login,
    profile,
    change_password_view,
    StudentUpdate,
    DashboardView,
    FacultyUpdateView,
    FacultyListView,
    StudentListView,
)

app_name = "accounts"

urlpatterns = [
    url(r'^profile/(?P<username>[\w.@+-]+)$', profile, name='profile'),
    url(r'^student/register/$', student_register, name="stud_register"),
    url(r'^faculty/register/$', faculty_register, name="faculty_register"),
    url(r'^faculties/$', FacultyListView.as_view(), name="faculty_list"),
    url(r'^students/$', StudentListView.as_view(), name="student_list"),
    url(r'^(?P<username>[\w.@+-]+)/dashboard/$',
        DashboardView.as_view(),
        name='dashboard'),
    url(r'^student/login/$', student_login, name='stud_login'),
    url(r'^faculty/login/$', faculty_login, name='faculty_login'),
    url(r'^student/(?P<username>[\w.@+-]+)/edit/$',
        StudentUpdate.as_view(),
        name='stud_update_profile'),
    url(r'^faculty/(?P<username>[\w.@+-]+)/edit/$',
        FacultyUpdateView.as_view(),
        name='faculty_update_profile'),
    url(r'^change_password/$', change_password_view, name='change_password'),
    url(r'^logout/$', logout_view, name='logout'),
]

thinktank/blogs/urls.py
from django.conf.urls import url
from .views import (
    BlogListView,
    BlogDetailView,
    CreateBlogView,
    BlogDeleteView,
    BlogUpdateView,
)

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog_list'),
    url(r'^(?P<pk>\d+)$', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    url(r'^new/$', CreateBlogView.as_view(), name='create_blog'),
    url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
        name='blog_delete'),
]

thinktank/events/urls.py
from django.conf.urls import url
from .views import (EventList, EventDetail, EventDelete,
                    event_post_view, event_update_view, delete_photo_of_event,
                    add_photo_on_event, add_video_on_event, delete_video_of_event)

app_name = 'events'

urlpatterns = [
    url(r'^new/$', event_post_view, name='post_event'),
    url(r'^$', EventList.as_view(), name='event_list'),
    url(r'(?P<pk>\d+)/$', EventDetail.as_view(), name='event_detail'),
    url(r'(?P<pk>\d+)/delete/$', EventDelete.as_view(), name='event_delete'),
    url(r'(?P<pk>\d+)/edit/$', event_update_view, name='event_edit'),
    url(r'(?P<pk>\d+)/photo/add/$',
        add_photo_on_event, name='add_photo'),
    url(r'(?P<pk>\d+)/video/add/$',
        add_video_on_event, name='add_video'),
    url(r'(?P<pk>\d+)/photo/(?P<pk1>\d+)/delete$',
        delete_photo_of_event, name='delete_photo'),
    url(r'(?P<pk>\d+)/video/(?P<pk1>\d+)/delete$',
        delete_video_of_event, name='delete_video'),
]

thinktank/forums/urls.py
from django.conf.urls import url
from .views import (
    ForumListView,
    ForumDetailView,
    ForumCreateView,
    ForumUpdateView,
    ForumDeleteView,
    add_comment_to_forum,
    reply_to_comment,
    comment_remove,
    reply_remove,
    CommentUpdateView,
    ReplyUpdateView,
)

app_name = 'forums'

urlpatterns = [
    url(r'^$', ForumListView.as_view(), name='forum_list'),
    url(r'^(?P<pk>\d+)$', ForumDetailView.as_view(), name='forum_detail'),
    url(r'^new/$', ForumCreateView.as_view(), name='create_forum'),
    url(r'^(?P<pk>\d+)/edit/$', ForumUpdateView.as_view(), name='update_forum'),
    url(r'^(?P<pk>\d+)/delete/$', ForumDeleteView.as_view(), name='delete_forum'),
    url(r'^(?P<pk>\d+)/comment/$',
        add_comment_to_forum,
        name="add_comment_to_forum"),
    url(r'^comment/(?P<pk>\d+)/edit/$',
        CommentUpdateView.as_view(),
        name="comment_update"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/delete/$',
        comment_remove,
        name="comment_remove"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/reply/$',
        reply_to_comment,
        name="reply_to_comment"),
    url(r'^comment/reply/(?P<pk>\d+)/edit/$',
        ReplyUpdateView.as_view(),
        name="reply_update"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/reply/(?P<pk2>\d+)/delete/$',
        reply_remove,
        name="reply_remove")
    # url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    # url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
    #     name='blog_delete'),
]

thinktank/materials/urls.py
from django.conf.urls import url
from django.views.generic import ListView
from .views import (add_material, MaterialDetailView, MaterialDeleteView,
                    add_image, delete_image, add_video, delete_video,
                    add_document, delete_document, delete_link, add_link,
                    add_gatematerial, material_view, download_material)

app_name = 'materials'

urlpatterns = [
    url(r'^$', material_view, name="material"),
    url(r'^download/(?P<file_name>.+)$', download_material),
    url(r'^create/$', add_material, name="add_material"),
    url(r'^gate/create/$', add_gatematerial, name="add_gatematerial"),
    url(r'^(?P<pk>\d+)/$',
        MaterialDetailView.as_view(), name="material_detail"),
    url(r'^(?P<pk>\d+)/delete$',
        MaterialDeleteView.as_view(), name="material_delete"),

    url(r'^(?P<pk>\d+)/document/add/$', add_document, name="add_document"),
    url(r'(?P<pk>\d+)/document/(?P<pk1>\d+)/delete$',
        delete_document, name='delete_document'),

    url(r'^(?P<pk>\d+)/link/add/$', add_link, name="add_link"),
    url(r'(?P<pk>\d+)/link/(?P<pk1>\d+)/delete$',
        delete_link, name='delete_link'),

    url(r'^(?P<pk>\d+)/image/add/$', add_image, name="add_image"),
    url(r'(?P<pk>\d+)/image/(?P<pk1>\d+)/delete$',
        delete_image, name='delete_image'),

    url(r'^(?P<pk>\d+)/video/add/$', add_video, name="add_video"),
    url(r'(?P<pk>\d+)/video/(?P<pk1>\d+)/delete$',
        delete_video, name='delete_video'),
]

thinktank/softwares/urls.py
from django.conf.urls import url
from .views import (SoftwareCreateView, SoftwareListView,
                    SoftwareDetailView, SoftwareUpdateView, SoftwareDeleteView,
                    ConfigurationCreateView, ConfigurationListView,
                    ConfigurationDetailView, ConfigurationUpdateView, ConfigurationDeleteView,
                    WorkingProjectCreateView, WorkingProjectListView,
                    WorkingProjectDetailView, WorkingProjectUpdateView, WorkingProjectDeleteView,
                    TechnologyCreateView, TechnologyListView,
                    TechnologyDetailView, TechnologyUpdateView, TechnologyDeleteView,)

app_name = "softwares"

urlpatterns = [
    url(r'^create/$', SoftwareCreateView.as_view(), name="create_software"),
    url(r'^$', SoftwareListView.as_view(), name="software_list"),
    url(r'^(?P<pk>\d+)/$', SoftwareDetailView.as_view(), name="software_detail"),
    url(r'^(?P<pk>\d+)/edit/$', SoftwareUpdateView.as_view(), name="software_update"),
    url(r'^(?P<pk>\d+)/delete/$',
        SoftwareDeleteView.as_view(), name="software_delete"),
    url(r'^confiuration/create/$', ConfigurationCreateView.as_view(),
        name="create_configuration"),
    url(r'^confiuration/$', ConfigurationListView.as_view(),
        name="configuration_list"),
    url(r'^confiuration/(?P<pk>\d+)/$',
        ConfigurationDetailView.as_view(), name="configuration_detail"),
    url(r'^confiuration/(?P<pk>\d+)/edit/$',
        ConfigurationUpdateView.as_view(), name="configuration_update"),
    url(r'^confiuration/(?P<pk>\d+)/delete/$',
        ConfigurationDeleteView.as_view(), name="configuration_delete"),

    url(r'^workingproject/create/$', WorkingProjectCreateView.as_view(),
        name="create_workingproject"),
    url(r'^workingproject/$', WorkingProjectListView.as_view(),
        name="workingproject_list"),
    url(r'^workingproject/(?P<pk>\d+)/$',
        WorkingProjectDetailView.as_view(), name="workingproject_detail"),
    url(r'^workingproject/(?P<pk>\d+)/edit/$',
        WorkingProjectUpdateView.as_view(), name="workingproject_update"),
    url(r'^workingproject/(?P<pk>\d+)/delete/$',
        WorkingProjectDeleteView.as_view(), name="workingproject_delete"),


    url(r'^technology/create/$', TechnologyCreateView.as_view(),
        name="create_technology"),
    url(r'^technology/$', TechnologyListView.as_view(),
        name="technology_list"),
    url(r'^technology/(?P<pk>\d+)/$',
        TechnologyDetailView.as_view(), name="technology_detail"),
    url(r'^technology/(?P<pk>\d+)/edit/$',
        TechnologyUpdateView.as_view(), name="technology_update"),
    url(r'^technology/(?P<pk>\d+)/delete/$',
        TechnologyDeleteView.as_view(), name="technology_delete"),
]

thinktank/accounts/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, get_user_model, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    UpdateView,
    TemplateView,
    ListView,
    DetailView,
)
from django.db.models import Q
from .models import Student, Faculty
from blogs.models import Blog
from forums.models import Forum
from events.models import Event
from materials.models import Material
from softwares.models import (
    Software, Configuration, WorkingProject, Technology)
from .forms import (
    StudentSignUpForm,
    UserLoginForm,
    FacultySignUpForm,
)

User = get_user_model()

# Create your views here.


def student_register(request, *args, **kwargs):
    if request.method == 'POST':
        form = StudentSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/account/student/login')
    else:
        form = StudentSignUpForm()
    return render(request, 'accounts/student/register.html', {'form': form})


def student_login(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user_obj = form.cleaned_data.get('user_obj')
            login(request, user_obj)
            return HttpResponseRedirect("/account/profile/{0}".format(
                user_obj.username))
    else:
        form = UserLoginForm()
    return render(request, 'accounts/student/login.html', {'form': form})


def faculty_register(request, *args, **kwargs):
    if request.method == 'POST':
        form = FacultySignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/account/faculty/login')
    else:
        form = FacultySignUpForm()
    return render(request, 'accounts/faculty/register.html', {'form': form})


def faculty_login(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user_obj = form.cleaned_data.get('user_obj')
            login(request, user_obj)
            return HttpResponseRedirect("/account/profile/{0}".format(
                user_obj.username))
    else:
        form = UserLoginForm()

    return render(request, 'accounts/faculty/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")


@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request,
                             "Your password was successfully updated!")
            return redirect('accounts:profile')
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})


def profile(request, username):
    user1 = User.objects.get(username=username)

    return render(request, 'accounts/profile.html', {'user1': user1})


class StudentUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = 'accounts/update_profile.html'
    fields = [
        'profile_picture',
        'first_name',
        'middle_name',
        'last_name',
        'gender',
        'date_of_birth',
        'college',
        'department',
        'university',
    ]

    def get_object(self):
        return get_object_or_404(
            Student, user__username__iexact=self.kwargs.get("username"))


class FacultyUpdateView(LoginRequiredMixin, UpdateView):
    model = Faculty
    template_name = 'accounts/update_profile.html'
    fields = [
        'profile_picture',
        'first_name',
        'middle_name',
        'last_name',
        'gender',
        'date_of_birth',
        'college',
        'department',
        'university',
    ]

    def get_object(self):
        return get_object_or_404(
            Faculty, user__username__iexact=self.kwargs.get("username"))

    def post(self, request, *args, **kwargs):
        return super(FacultyUpdateView, self).post(request, *args, **kwargs)


class FacultyListView(ListView):
    model = Faculty
    template_name = 'accounts/faculty/faculty_list.html'

    def get_queryset(self):
        return Faculty.objects.all()


class StudentListView(ListView):
    model = Student
    template_name = 'accounts/student/student_list.html'

    def get_queryset(self):
        return Student.objects.all()


class DashboardView(LoginRequiredMixin, TemplateView):
    login_url = '/'
    template_name = 'accounts/faculty/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_blog_list'] = Blog.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        context['my_forum_list'] = Forum.objects.filter(
            questioner__username__iexact=self.request.user)
        context['my_event_list'] = Event.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        context['my_material_list'] = Material.objects.filter(
            Q(is_of_gate=False),
            Q(faculty__user__username__iexact=self.request.user.faculty)
        )
        context['my_gatematerial_list'] = Material.objects.filter(
            Q(is_of_gate=True),
            Q(faculty__user__username__iexact=self.request.user.faculty)
        )
        context['my_software_list'] = Software.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        context['my_config_list'] = Configuration.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        context['my_workprj_list'] = WorkingProject.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        context['my_tech_list'] = Technology.objects.filter(
            user__user__username__iexact=self.request.user.faculty)
        return context

thinktank/accounts/templates/accounts/faculty/dashboard.html
{% extends 'thinktank/base.html' %}

{% block title %}Dashboard{% endblock%}

{% block content %}
{% if user.is_faculty %}
<h4>Your Dashboard</h4>
<hr>
<br>

<h5>Blogs</h5>
<hr>
<ul>
    {% for blog in my_blog_list %}
    <li>
        <a href="{% url 'blogs:blog_detail' pk=blog.pk%}">{{ blog.title }}</a>
        - posted on: {{blog.created_date}}
    </li>
    {% empty %}
    <p>No blogs.</p>
    {% endfor %}
</ul>
<hr>
<a class="btn btn-dark" href="{% url 'blogs:create_blog' %}" style="color:white">
    Post a Blog
</a>
{%endif%}
<hr>


<h5>Forums</h5>
<hr>
<ul>
    {% for forum in my_forum_list %}
    <li>
        <a href="{% url 'forums:forum_detail' pk=forum.pk%}">{{ forum.q_title }}</a>
        - posted on: {{forum.asked_on}}
    </li>
    {% empty %}
    <p>No forums.</p>
    {% endfor %}
</ul>
<hr>
<a class="btn btn-dark" href="{% url 'forums:create_forum' %}" style="color:white">
    Ask on Forum
</a>
<hr>


<h5>Events</h5>
<hr>
<ul>
    {% for event in my_event_list %}
    <li>
        <a href="{% url 'events:event_detail' pk=event.pk%}">{{ event.title }}</a>
    </li>
    {% empty %}
    <p>No events.</p>
    {% endfor %}
</ul>
<hr>
<a class="btn btn-dark" href="{% url 'events:post_event' %}" style="color:white">
    Add Event
</a>
<hr>


<h5>Materials</h5>
<hr>
<ul>
    {% for material in my_material_list %}
    <li>
        <a href="{% url 'materials:material_detail' pk=material.pk%}">
            {{ material.title}}
        </a>
    </li>
    {% empty %}
    <p>No Materials.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'materials:add_material' %}" style="color:white">
    Add Notes
</a>

<hr>

<h5>Gate Materials</h5>
<hr>
<ul>
    {% for gmaterial in my_gatematerial_list %}
    <li>
        <a href="{% url 'materials:material_detail' pk=gmaterial.pk%}">
            {{ gmaterial.title}}
        </a>
    </li>
    {% empty %}
    <p>No Materials.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'materials:add_gatematerial' %}" style="color:white">
    Add Gate Notes
</a>
<hr>

<h5>Softwares</h5>
<hr>
<ul>
    {% for software in my_software_list %}
    <li>
        <a href="{% url 'softwares:software_detail' pk=software.pk%}">
            {{ software.title}}
        </a>
    </li>
    {% empty %}
    <p>No softwares.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'softwares:create_software' %}" style="color:white">
    Add Software
</a>
<hr>

<h5>Configurations</h5>
<hr>
<ul>
    {% for config in my_config_list %}
    <li>
        <a href="{% url 'softwares:configuration_detail' pk=config.pk%}">
            {{ config.title}}
        </a>
    </li>
    {% empty %}
    <p>No configurations.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'softwares:create_configuration' %}" style="color:white">
    Add Configuration
</a>
<hr>

<h5>Working Projects</h5>
<hr>
<ul>
    {% for prj in my_workprj_list %}
    <li>
        <a href="{% url 'softwares:workingproject_detail' pk=prj.pk%}">
            {{ prj.title}}
        </a>
    </li>
    {% empty %}
    <p>No projects.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'softwares:create_workingproject' %}" style="color:white">
    Add Project
</a>
<hr>

<h5>Technology</h5>
<hr>
<ul>
    {% for tech in my_tech_list %}
    <li>
        <a href="{% url 'softwares:technology_detail' pk=tech.pk%}">
            {{ tech.title}}
        </a>
    </li>
    {% empty %}
    <p>No technology.</p>
    {% endfor %}
</ul>
<a class="btn btn-dark" href="{% url 'softwares:create_technology' %}" style="color:white">
    Add Technology
</a>
<hr>

{% endblock %}

thinktank/accounts/templates/accounts/faculty/faculty_list.html
{% extends 'thinktank/base.html' %}

{% block title %}Faculties{% endblock%}
{% load static %}
{% block link %}
<link rel="stylesheet" href={% static "custom/css/style1.css" %} />
{% endblock %}

{% block content %}
<h4>Faculties</h4>
<hr>
<ul class="list-unstyled"></ul>
{% for faculty in faculty_list %}
<li class="media display_card">
    {% if faculty.profile_picture %}
    <img src="{{ faculty.profile_picture.url }}" alt="picture" width="50" class="mr-3" />
    {%endif%}
    {% if not faculty.profile_picture %}
    <img src="/media/icons/person_icon.png" style="background:#ddd;" width="50" class="mr-3" />
    {%endif%}
    <div class="media-body">
        <h5 class="mt-0 mb-1"><a href="{% url 'accounts:profile' username=faculty%}">{{ faculty.get_full_name }}</a>
        </h5>
        <p style="margin:0; font-size: 14px;">{{faculty.department}}, {{faculty.university}}</p>
    </div>
</li>
{% empty%}
<h2>No faculty. :(</h2>
{% endfor%}
</ul>
{% endblock %}

thinktank/accounts/templates/accounts/faculty/login.html
{% extends 'thinktank/base.html' %}

{% block title %}Faculty Login{% endblock%}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn primary-btn" value="Log In" />
</form>
{% endblock %}

thinktank/accounts/templates/accounts/faculty/register.html
{% extends 'thinktank/base.html' %}

{% block title %}Faculty Registration{% endblock%}

{% block content %}
<h1>Register Faculty</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn primary-btn" value="Register">
</form>
{% endblock %}