thinktank/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    student_register,
    student_login,
    logout_view,
    faculty_register,
    faculty_login,
    profile,
    change_password_view,
    StudentUpdate,
    DashboardView,
    FacultyUpdateView,
    FacultyListView,
    StudentListView,
)

app_name = "accounts"

urlpatterns = [
    url(r'^profile/(?P<username>[\w.@+-]+)$', profile, name='profile'),
    url(r'^student/register/$', student_register, name="stud_register"),
    url(r'^faculty/register/$', faculty_register, name="faculty_register"),
    url(r'^faculties/$', FacultyListView.as_view(), name="faculty_list"),
    url(r'^students/$', StudentListView.as_view(), name="student_list"),
    url(r'^(?P<username>[\w.@+-]+)/dashboard/$',
        DashboardView.as_view(),
        name='dashboard'),
    url(r'^student/login/$', student_login, name='stud_login'),
    url(r'^faculty/login/$', faculty_login, name='faculty_login'),
    url(r'^student/(?P<username>[\w.@+-]+)/edit/$',
        StudentUpdate.as_view(),
        name='stud_update_profile'),
    url(r'^faculty/(?P<username>[\w.@+-]+)/edit/$',
        FacultyUpdateView.as_view(),
        name='faculty_update_profile'),
    url(r'^change_password/$', change_password_view, name='change_password'),
    url(r'^logout/$', logout_view, name='logout'),
]

thinktank/blogs/urls.py
from django.conf.urls import url
from .views import (
    BlogListView,
    BlogDetailView,
    CreateBlogView,
    BlogDeleteView,
    BlogUpdateView,
)

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog_list'),
    url(r'^(?P<pk>\d+)$', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    url(r'^new/$', CreateBlogView.as_view(), name='create_blog'),
    url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
        name='blog_delete'),
]

thinktank/materials/urls.py
from django.conf.urls import url
from django.views.generic import ListView
from .views import (add_material, MaterialDetailView, MaterialDeleteView,
                    add_image, delete_image, add_video, delete_video,
                    add_document, delete_document, delete_link, add_link,
                    add_gatematerial, material_view, download_material)

app_name = 'materials'

urlpatterns = [
    url(r'^$', material_view, name="material"),
    url(r'^download/(?P<file_name>.+)$', download_material),
    url(r'^create/$', add_material, name="add_material"),
    url(r'^gate/create/$', add_gatematerial, name="add_gatematerial"),
    url(r'^(?P<pk>\d+)/$',
        MaterialDetailView.as_view(), name="material_detail"),
    url(r'^(?P<pk>\d+)/delete$',
        MaterialDeleteView.as_view(), name="material_delete"),

    url(r'^(?P<pk>\d+)/document/add/$', add_document, name="add_document"),
    url(r'(?P<pk>\d+)/document/(?P<pk1>\d+)/delete$',
        delete_document, name='delete_document'),

    url(r'^(?P<pk>\d+)/link/add/$', add_link, name="add_link"),
    url(r'(?P<pk>\d+)/link/(?P<pk1>\d+)/delete$',
        delete_link, name='delete_link'),

    url(r'^(?P<pk>\d+)/image/add/$', add_image, name="add_image"),
    url(r'(?P<pk>\d+)/image/(?P<pk1>\d+)/delete$',
        delete_image, name='delete_image'),

    url(r'^(?P<pk>\d+)/video/add/$', add_video, name="add_video"),
    url(r'(?P<pk>\d+)/video/(?P<pk1>\d+)/delete$',
        delete_video, name='delete_video'),
]

thinktank/materials/models.py
from django.db import models
from django.shortcuts import redirect, reverse
from accounts.models import Faculty
import uuid
import os
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile
from django.dispatch import receiver
# Create your models here.


def store_thumnail(instance, filename):
    ext = filename.split('.')[-1]
    first = filename.split('.')[0]
    filename = "mi_thumnail_{}.{}".format(first, ext)
    return os.path.join('images', 'material', 'thumbnail', filename)


def upload_img_to_with_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "materialimage_{}.{}".format(str(uuid.uuid4()), ext)
    return os.path.join('images', 'material', filename)


def upload_doc_to_with_name(instance, filename):
    return os.path.join('documents', 'material', filename)


def upload_vid_to_with_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "materialvideo_{}.{}".format(str(uuid.uuid4()), ext)
    return os.path.join('videos', 'material', filename)


class Material(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    faculty = models.ForeignKey(
        Faculty, on_delete=models.CASCADE, related_name="materials")
    is_of_gate = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('materials:material_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "{} by {}".format(self.title, self.faculty.user.username)


class MaterialDocument(models.Model):
    material = models.ForeignKey(
        Material, on_delete=models.CASCADE, related_name="documents")
    document = models.FileField(
        upload_to=upload_doc_to_with_name, blank=True, null=True)

    def __str__(self):
        return "{} [file] by {}".format(self.material.title, self.material.faculty.user.username)

    def get_filename(self):
        return self.document.name.split('/')[-1]


class MaterialLink(models.Model):
    material = models.ForeignKey(
        Material, on_delete=models.CASCADE, related_name="links")
    link = models.URLField()

    def __str__(self):
        return "{} [link] by {}".format(self.material.title, self.material.faculty.user.username)


class MaterialVideo(models.Model):
    material = models.ForeignKey(
        Material, on_delete=models.CASCADE, related_name="videos")
    video = models.FileField(
        upload_to=upload_vid_to_with_name, blank=True, null=True)

    def __str__(self):
        return "{} [video] by {}".format(self.material.title, self.material.faculty.user.username)


class MaterialImage(models.Model):
    material = models.ForeignKey(
        Material, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(
        upload_to=upload_img_to_with_name, blank=True, null=True)
    thumbnail = models.ImageField(upload_to=store_thumnail,
                                  blank=True, null=True)

    def __str__(self):
        return "{} [img] by {}".format(self.material.title, self.material.faculty.user.username)

    def create_thumbnail(self):

        if not self.image:
            return

        # Set our max thumbnail size in a tuple (max width, max height)
        THUMBNAIL_SIZE = (200, 200)

        DJANGO_TYPE = self.image.file.content_type

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'

        # Open original photo which we want to thumbnail using PIL's Image
        # image = Image.open(BytesIO(self.photo.read()))
        r = BytesIO(self.image.read())  # Using BytesIO instead of StringIO
        fullsize_image = Image.open(r)
        new_image = fullsize_image.copy()

        # We use our PIL Image object to create the thumbnail, which already
        # has a thumbnail() convenience method that contrains proportions.
        # Additionally, we use Image.ANTIALIAS to make the image look better.
        # Without antialiasing the image pattern artifacts may result.
        new_image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        # Save the thumbnail
        temp_handle = BytesIO()
        new_image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)

        # Save image to a SimpleUploadedFile which can be saved into
        # ImageField
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                                 temp_handle.read(), content_type=DJANGO_TYPE)
        # Save SimpleUploadedFile into image field
        self.thumbnail.save('{}_thumbnail.{}'.format(
                            os.path.splitext(suf.name)[0],
                            FILE_EXTENSION), suf, save=False)

    def save(self):
        # create a thumbnail
        self.create_thumbnail()
        super(MaterialImage, self).save()


@receiver(models.signals.post_delete, sender=MaterialImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)
    if instance.thumbnail:
        if os.path.isfile(instance.thumbnail.path):
            os.remove(instance.thumbnail.path)


@receiver(models.signals.post_delete, sender=MaterialVideo)
def auto_delete_video_on_delete(sender, instance, **kwargs):
    if instance.video:
        if os.path.isfile(instance.video.path):
            os.remove(instance.video.path)


@receiver(models.signals.post_delete, sender=MaterialDocument)
def auto_delete_document_on_delete(sender, instance, **kwargs):
    if instance.document:
        if os.path.isfile(instance.document.path):
            os.remove(instance.document.path)

thinktank/materials/forms.py
from django import forms
from .models import Material, MaterialImage, MaterialLink, MaterialDocument, MaterialVideo


class CreateMaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ('title', 'description',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'You can leave it empty'}),
        }


class DocumentForm(forms.ModelForm):
    class Meta:
        model = MaterialDocument
        fields = ('document',)


class LinkForm(forms.ModelForm):
    class Meta:
        model = MaterialLink
        fields = ('link',)


class ImageForm(forms.ModelForm):
    class Meta:
        model = MaterialImage
        fields = ('image',)


class VideoForm(forms.ModelForm):
    class Meta:
        model = MaterialVideo
        fields = ('video',)

thinktank/materials/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.shortcuts import redirect
from .models import (MaterialDocument, MaterialLink,
                     MaterialVideo, MaterialImage, Material)
from .forms import (CreateMaterialForm, ImageForm,
                    VideoForm, DocumentForm, LinkForm,)
from django.views.generic import DetailView, DeleteView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.http import HttpResponse, Http404
import os
import mimetypes


# Create your views here.
# departments = ["Computer Science and Enginnering", "Mechanical Enginnering", "Civil Enginnering", "Electronics \
#               and Communication Enginnering", "Electrical and Electronic Enginnering"]


def material_view(request):
    notes = Material.objects.filter(is_of_gate=False)
    gates = Material.objects.filter(is_of_gate=True)
    context = {'notes': notes, 'gates': gates}
    return render(request, 'materials/material.html', context=context)


# def department_wise_material(request):
#     return render(request, 'materials/department_page.html')

def add_material(request):
    if request.method == "POST":
        form = CreateMaterialForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.faculty = request.user.faculty
            form.save()
            return redirect("materials:material_detail", pk=form.pk)
    else:
        form = CreateMaterialForm()

    return render(request, template_name="materials/add_material_page.html", context={'form': form})


def download_material(request, file_name):
    file_ext = file_name.split(".")[-1]
    file_path = os.path.join(
        settings.MEDIA_ROOT, "documents", "material", file_name)
    file_mimetype = mimetypes.guess_type(file_path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(
                fh.read(), content_type=file_mimetype[0])
            response['Content-Disposition'] = 'inline; filename=' + \
                os.path.basename(file_path)
            return response
    else:
        raise Http404


def add_gatematerial(request):
    if request.method == "POST":
        form = CreateMaterialForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.is_of_gate = True
            form.faculty = request.user.faculty
            form.save()
            return redirect("materials:material_detail", pk=form.pk)
    else:
        form = CreateMaterialForm()

    return render(request, template_name="materials/add_material_page.html", context={'form': form})


class MaterialDetailView(DetailView):
    model = Material


class MaterialDeleteView(LoginRequiredMixin, DeleteView):
    model = Material

    def get_success_url(self):
        return reverse_lazy('accounts:dashboard', kwargs={
            'username': self.request.user.username})


@login_required
def add_document(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            doc = request.FILES['document']
            form = MaterialDocument(material=material, document=doc)
            form.save()
            return redirect('materials:material_detail', pk=pk)
    else:
        form = DocumentForm()
    return render(request, 'materials/add_image.html', {'form': form})


@login_required
def delete_document(request, pk, pk1):
    doc = get_object_or_404(MaterialDocument, pk=pk1)
    doc.delete()
    return redirect('materials:material_detail', pk=pk)


@login_required
def add_link(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if request.method == "POST":
        form = LinkForm(request.POST)
        if form.is_valid():
            link = form.cleaned_data['link']
            form = MaterialLink(material=material, link=link)
            form.save()
            return redirect('materials:material_detail', pk=pk)
    else:
        form = LinkForm()
    return render(request, 'materials/add_link.html', {'form': form})


@login_required
def delete_link(request, pk, pk1):
    link = get_object_or_404(MaterialLink, pk=pk1)
    link.delete()
    return redirect('materials:material_detail', pk=pk)


@login_required
def add_video(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if request.method == "POST":
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            vid = request.FILES['video']
            form = MaterialVideo(material=material, video=vid)
            form.save()
            return redirect('materials:material_detail', pk=pk)

    else:
        form = VideoForm()
    return render(request, 'materials/add_image.html', {'form': form})


@login_required
def delete_video(request, pk, pk1):
    video = get_object_or_404(MaterialVideo, pk=pk1)
    video.delete()
    return redirect('materials:material_detail', pk=pk)


@login_required
def add_image(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            img = request.FILES['image']
            form = MaterialImage(material=material, image=img)
            form.save()
            return redirect('materials:material_detail', pk=pk)
    else:
        form = ImageForm()
    return render(request, 'materials/add_image.html', {'form': form})


@login_required
def delete_image(request, pk, pk1):
    photo = get_object_or_404(MaterialImage, pk=pk1)
    photo.delete()
    return redirect('materials:material_detail', pk=pk)

thinktank/materials/templates/materials/add_image.html
{% extends 'thinktank/base.html' %}

{% block title %}Add Photo{% endblock%}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" id="" value="Add" class="btn">
</form>

{% endblock %}

thinktank/materials/templates/materials/add_link.html
{% extends 'thinktank/base.html' %}

{% block title %}Add Link{% endblock%}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" id="" value="Add" class="btn">
</form>

{% endblock %}

thinktank/materials/templates/materials/add_material_page.html
{% extends 'thinktank/base.html' %}

{% block content %}
<h2>Add material</h2>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Add Files">
</form>

{% endblock %}

thinktank/materials/templates/materials/material.html
{% extends 'thinktank/base.html' %}

{% block title%}Material{%endblock%}

{% block content %}
<h4>Notes</h4>
<hr>
{% for note in notes %}
<p style="background: white; padding: 10px; font-size: 18px;">
    <a href="{% url 'materials:material_detail' pk=note.pk%}">{{note.title}}</a>
    <text style="font-size: 14px;">- by <a style="color: maroon;"
            href="{% url 'accounts:profile' username=note.faculty%}">{{note.faculty.get_full_name}}</a></text> <br>
    <span class="badge badge-primary">{{note.faculty.department}}</span>
    <br>
    <br><a href="{% url 'materials:material_detail' pk=note.pk%}" class="btn btn-success">Detail</a>
</p>
{%empty%}
<p>no notes! :(</p>
{%endfor%}
<h4>Gate Materials</h4>
<hr>
{% for gate in gates %}
<p style="background: white; padding: 10px; font-size: 18px;">
    <a href="{% url 'materials:material_detail' pk=gate.pk%}">{{gate.title}}</a>
    <text style="font-size: 14px;">by <a style="color: maroon;"
            href="{% url 'accounts:profile' username=gate.faculty%}">{{ gate.faculty.get_full_name}}</a></text> <br>
    <span class="badge badge-primary">{{gate.faculty.department}}</span>
    <br>
    <br><a href="{% url 'materials:material_detail' pk=gate.pk%}" class="btn btn-success">Detail</a>
</p>
{%empty%}
<p>no notes updated yet.</p>
{%endfor%}
{%endblock%}

thinktank/materials/templates/materials/material_confirm_delete.html
{% extends 'thinktank/base.html' %}

{% block title %}Material Delete{% endblock%}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure want to delete? {{object}}</p>
    <input type="submit" value="Yes" class="btn">
</form>
{% endblock %}

thinktank/materials/templates/materials/material_detail.html
{% extends 'thinktank/base.html' %}

{% block title%}Material{%endblock%}

{% block content %}
<h2>{{material.title}}</h2>
<p class="showing_name">By:
    <a href="{% url 'accounts:profile' username=material.faculty%}">
        {{material.faculty.user.get_full_name}} <span class="badge badge-primary">{{material.faculty.department}}</span>
    </a>
</p>
<hr>
<p>Description: <br>{{material.description}}</p>
{% if request.user.is_authenticated and request.user.is_faculty %}
<p><a href="{% url 'materials:material_delete' pk=material.pk %}">Delete</a></p>
{% endif %}
<p>Attachments :</p>
<div class="blocks">
    <h5>Documents
        {% if request.user.is_authenticated and request.user == material.faculty.user %}
        <a href="{% url 'materials:add_document' pk=material.pk%}">
            <img style="width:25;float: right;" src="/media/icons/add_video_icon.png" alt="add files">
        </a>
        {%endif%}
    </h5>
    {% for material_doc in material.documents.all %}
    <div class="material_container">
        {% if request.user == material.faculty.user %}
        <p style="margin: 0 10 0 0; text-align: right;">
            <a onclick="return confirm('Are you sure you want to delete this?')"
                href="{% url 'materials:delete_document' pk=material.pk pk1=material_doc.pk%}">X</a>
        </p>
        {%endif%}
        <a href="/material/download/{{material_doc.get_filename}}">{{material_doc.get_filename}}</a>

    </div>
    {% empty %}
    No documents
    {% endfor %}

</div>
<div class="blocks">
    <h5>Links
        {% if request.user.is_authenticated and request.user == material.faculty.user %}
        <a href="{% url 'materials:add_link' pk=material.pk%}">
            <img style="width:25;float: right;" src="/media/icons/add_video_icon.png" alt="add links">
        </a>
        {%endif%}
    </h5>
    {% for material_link in material.links.all %}
    <div class="material_container">
        {% if request.user == material.faculty.user %}
        <p style="margin: 0 10 0 0; text-align: right;">
            <a onclick="return confirm('Are you sure you want to delete this?')"
                href="{% url 'materials:delete_link' pk=material.pk pk1=material_link.pk%}">X</a>
        </p>
        {%endif%}
        {{ material_link.link }}

    </div>
    {% empty %}
    No links
    {% endfor %}

</div>
<div class="blocks">
    <h5>Videos
        {% if request.user.is_authenticated and request.user == material.faculty.user %}
        <a href="{% url 'materials:add_video' pk=material.pk%}">
            <img style="width:25;float: right;" src="/media/icons/add_video_icon.png" alt="add video">
        </a>
        {%endif%}
    </h5>

    {% for material_video in material.videos.all %}
    <div class="material_container">
        {% if request.user == material.faculty.user %}
        <p style="margin: 0 10 0 0; text-align: right;">
            <a onclick="return confirm('Are you sure you want to delete this?')"
                href="{% url 'materials:delete_video' pk=material.pk pk1=material_video.pk%}">X</a>
        </p>
        {%endif%}
        <video width="200" controls muted>
            <source src="{{material_video.video.url}}" type="video/mp4">
            </source>
        </video>

    </div>
    {% empty %}
    No videos
    {% endfor %}

</div>
<div class="blocks">
    <h5>Images
        {% if request.user.is_authenticated and request.user == material.faculty.user %}
        <a href="{% url 'materials:add_image' pk=material.pk%}">
            <img style="width:25;float: right;" src="/media/icons/add_img.png" alt="add image">
        </a>
        {%endif%}
    </h5>
    {% for material_image in material.images.all %}
    <div class="material_container">
        {% if request.user == material.faculty.user %}
        <p style="margin: 0 10 0 0; text-align: right;">
            <a onclick="return confirm('Are you sure you want to delete this?')"
                href="{% url 'materials:delete_image' pk=material.pk pk1=material_image.pk%}">X</a>
        </p>
        {%endif%}
        <a href="{{material_image.image.url}}"><img src="{{material_image.thumbnail.url}}" alt=""></a>

    </div>
    {% empty %}
    No images
    {% endfor %}

</div>

{% endblock %}