thinktank/blogs/urls.py
from django.conf.urls import url
from .views import (
    BlogListView,
    BlogDetailView,
    CreateBlogView,
    BlogDeleteView,
    BlogUpdateView,
)

app_name = 'blogs'

urlpatterns = [
    url(r'^$', BlogListView.as_view(), name='blog_list'),
    url(r'^(?P<pk>\d+)$', BlogDetailView.as_view(), name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    url(r'^new/$', CreateBlogView.as_view(), name='create_blog'),
    url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
        name='blog_delete'),
]

thinktank/forums/urls.py
from django.conf.urls import url
from .views import (
    ForumListView,
    ForumDetailView,
    ForumCreateView,
    ForumUpdateView,
    ForumDeleteView,
    add_comment_to_forum,
    reply_to_comment,
    comment_remove,
    reply_remove,
    CommentUpdateView,
    ReplyUpdateView,
)

app_name = 'forums'

urlpatterns = [
    url(r'^$', ForumListView.as_view(), name='forum_list'),
    url(r'^(?P<pk>\d+)$', ForumDetailView.as_view(), name='forum_detail'),
    url(r'^new/$', ForumCreateView.as_view(), name='create_forum'),
    url(r'^(?P<pk>\d+)/edit/$', ForumUpdateView.as_view(), name='update_forum'),
    url(r'^(?P<pk>\d+)/delete/$', ForumDeleteView.as_view(), name='delete_forum'),
    url(r'^(?P<pk>\d+)/comment/$',
        add_comment_to_forum,
        name="add_comment_to_forum"),
    url(r'^comment/(?P<pk>\d+)/edit/$',
        CommentUpdateView.as_view(),
        name="comment_update"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/delete/$',
        comment_remove,
        name="comment_remove"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/reply/$',
        reply_to_comment,
        name="reply_to_comment"),
    url(r'^comment/reply/(?P<pk>\d+)/edit/$',
        ReplyUpdateView.as_view(),
        name="reply_update"),
    url(r'^(?P<pk>\d+)/comment/(?P<pk1>\d+)/reply/(?P<pk2>\d+)/delete/$',
        reply_remove,
        name="reply_remove")
    # url(r'^(?P<pk>\d+)/edit/$', BlogUpdateView.as_view(), name='blog_update'),
    # url(r'^(?P<pk>\d+)/delete/$', BlogDeleteView.as_view(),
    #     name='blog_delete'),
]

thinktank/homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = "homepage"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

thinktank/forums/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.shortcuts import reverse

TAGS = (('CS',
         'Computer Science'), ('Mech',
                               'Mechanical'),
        ('EE', 'Electrical and Electronics'),
        ('C', 'Civil'),
        ('EC', 'Electronics and Communication'),
        ('O', 'Other'))

# Create your models here.
User = get_user_model()


class Forum(models.Model):
    questioner = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.CharField(max_length=5, choices=TAGS, default='O')
    q_title = models.CharField(max_length=255)
    detail = models.TextField()
    asked_on = models.DateTimeField(auto_now_add=True)
    last_edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.q_title

    def get_absolute_url(self):
        return reverse('forums:forum_detail', kwargs={'pk': self.pk})

    class Meta:
        unique_together = ['questioner', 'q_title', 'detail']


class Comment(models.Model):
    forum = models.ForeignKey(
        Forum, on_delete=models.CASCADE, related_name='comments')
    commented_on = models.DateTimeField(auto_now_add=True)
    edited_on = models.DateTimeField(auto_now=True)
    text = models.TextField()
    reply_to = models.ForeignKey(
        User, related_name='reply_to', on_delete=models.CASCADE)
    reply_by = models.ForeignKey(
        User, related_name='reply_by', on_delete=models.CASCADE)

    def __str__(self):
        return "{} commented on {} to {}".format(self.reply_by, self.forum,
                                                 self.reply_to)

    def get_absolute_url(self):
        return reverse('forums:forum_detail', kwargs={'pk': self.forum.pk})


class CommentOnComment(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='sub_comments')
    commented_on = models.DateTimeField(auto_now_add=True)
    edited_on = models.DateTimeField(auto_now=True)
    text = models.TextField()
    reply_to = models.ForeignKey(
        User, related_name='comment_reply_to', on_delete=models.CASCADE)
    reply_by = models.ForeignKey(
        User, related_name='comment_reply_by', on_delete=models.CASCADE)

    def __str__(self):
        return "{} replied on {} ".format(
            self.reply_by, self.comment.forum)

    def get_absolute_url(self):
        return reverse(
            'forums:forum_detail', kwargs={'pk': self.comment.forum.pk})

thinktank/forums/forms.py
from django import forms

from .models import Forum, Comment, CommentOnComment


class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ('q_title', 'detail', 'tag',)

        widgets = {
            'q_title': forms.TextInput(attrs={'class': 'form-control'}),
            'detail': forms.Textarea(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

        widgets = {'text': forms.Textarea(attrs={'class': 'form-control'})}


class CommentOnCommentForm(forms.ModelForm):
    class Meta:
        model = CommentOnComment
        fields = ('text', )

        widgets = {'text': forms.Textarea(attrs={'class': 'form-control'})}

thinktank/forums/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    TemplateView,
    ListView,
    DeleteView,
    DetailView,
    UpdateView,
    CreateView,
)

from .forms import ForumForm, CommentForm, CommentOnCommentForm
from .models import Comment, Forum, CommentOnComment


# Create your views here.
class ForumListView(ListView):
    model = Forum

    def get_queryset(self):
        return Forum.objects.all()


class ForumDetailView(DetailView):
    model = Forum


class ForumCreateView(LoginRequiredMixin, CreateView):
    login_url = "/"
    model = Forum
    form_class = ForumForm
    redirect_field_name = 'forums/forum_detail.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.questioner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ForumUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/"
    model = Forum
    redirect_field_name = 'forums/forum_detail.html'
    form_class = ForumForm


class ForumDeleteView(LoginRequiredMixin, DeleteView):
    login_url = "/"
    model = Forum
    success_url = reverse_lazy('forums:forum_list')


# comments
@login_required
def add_comment_to_forum(request, pk):
    forum = get_object_or_404(Forum, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.forum = forum
            comment.reply_to = forum.questioner
            comment.reply_by = request.user
            comment.save()
            return redirect('forums:forum_detail', pk=forum.pk)
    else:
        form = CommentForm()
    return render(request, 'forums/comment_form.html', {'form': form})


@login_required
def comment_remove(request, pk, pk1):
    comment = get_object_or_404(Comment, pk=pk1)
    forum_pk = comment.forum.pk
    comment.delete()
    return redirect('forums:forum_detail', pk=forum_pk)


# reply on comments
@login_required
def reply_to_comment(request, **kwargs):
    comment = get_object_or_404(Comment, pk=kwargs.get('pk1'))
    if request.method == 'POST':
        form = CommentOnCommentForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = comment
            reply.reply_to = comment.reply_by
            reply.reply_by = request.user
            reply.save()
            return redirect('forums:forum_detail', pk=comment.forum.pk)
    else:
        form = CommentOnCommentForm()
    return render(request, 'forums/comment_form.html', {'form': form})


@login_required
def reply_remove(request, pk, pk1, pk2):
    sub_comment = get_object_or_404(CommentOnComment, pk=pk2)
    sub_comment.delete()
    return redirect('forums:forum_detail', pk=pk)


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/"
    model = Comment
    redirect_field_name = 'forums/forum_detail.html'
    form_class = CommentForm


class ReplyUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/"
    model = CommentOnComment
    redirect_field_name = 'forums/forum_detail.html'
    form_class = CommentOnCommentForm
    template_name = 'forums/comment_form.html'

thinktank/forums/templates/forums/comment_form.html
{% extends 'thinktank/base.html' %}

{% block title %}Comment{% endblock%}

{% block content %}

<h2>Comment</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Reply" class="btn btn-primary">
</form>

{% endblock %}

thinktank/forums/templates/forums/forum_confirm_delete.html
{% extends 'thinktank/base.html' %}

{% block title %}Delete?{% endblock%}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure want to delete? {{ object }}</p>
    {{form.as_p}}
    <input class="btn btn-danger" type="submit" value="Confirm">
</form> {% endblock %}

thinktank/forums/templates/forums/forum_detail.html
{% extends 'thinktank/base.html' %}

{% block title %}Forum Detail{% endblock%}

{% block content %}
<h4>Q: {{forum.q_title}}</h4>
<p style="font-size:12px; font-style: italic;">Asked by: {{forum.questioner}}</p>
<p>{{forum.detail|linebreaks}}</p>

{% if request.user == forum.questioner %}
<a href="{% url 'forums:update_forum' pk=forum.pk%}">Edit</a> |
<a href="{%url 'forums:delete_forum' pk=forum.pk%}">Delete</a>
{% endif%}

<hr>
{% if not user.is_authenticated %}
<p style="text-align: right"> <a href="{% url 'homepage:index'%}">Login to Reply</a> </p>
{% endif %}
{% if user.is_authenticated %}
<p style="text-align: right"> <a class="btn btn-secondary" href="{% url 'forums:add_comment_to_forum' pk=forum.pk%}">Reply</a>
</p>
{% endif %}
<hr>
{% for comment in forum.comments.all %}
<div style="background:#ddd; padding-left: 10px;padding-right:10px; ">
    <p style="font-size:18px;">{{comment.text|safe}}</p>
    <p style="font-size:12px; font-style: italic;">
        Reply by: {{comment.reply_by}}
        | {{ comment.commented_on|timesince}} ago
        | edited on: {{comment.edited_on}}
    </p>
    <p style="text-align: right">
        {% if not user.is_authenticated %}
        Login to Reply |
        {% endif %}
        <a href="{% url 'forums:reply_to_comment' pk=forum.pk pk1=comment.pk%}">Reply</a>
        {% if request.user == comment.reply_by %}
        | <a href="{% url 'forums:comment_update' pk=comment.pk%}">Edit</a>
        {% endif %}
        {% if request.user == comment.reply_by or request.user == comment.forum.questioner%}
        | <a onclick="return confirm('Are you sure you want to delete this?')" href="{% url 'forums:comment_remove' pk=forum.pk pk1=comment.pk%}">Delete</a>
        {% endif%}
    </p>
</div>
{% for sub_comment in comment.sub_comments.all %}
<div style="margin-left:50px;background: #dddeee;padding-left: 10px;padding-right:10px;">
    <p style="font-size:18px;">{{sub_comment.text|safe}}</p>
    <p style="font-size:12px; font-style: italic;">
        Reply by: {{sub_comment.reply_by}}
        | {{ sub_comment.commented_on | timesince}} ago
        | edited on: {{sub_comment.edited_on}}
    </p>
    <p style="text-align: right">
        {% if not user.is_authenticated %}
        Login to Reply |
        {% endif %}
        <a href="{% url 'forums:reply_to_comment' pk=forum.pk pk1=comment.pk%}">Reply</a>
        {% if request.user == sub_comment.reply_by %}
        | <a href="{% url 'forums:reply_update' pk=sub_comment.pk%}">Edit</a>
        {% endif %}
        {% if request.user == sub_comment.reply_by or request.user == sub_comment.comment.forum.questioner%}
        | <a onclick="return confirm('Are you sure you want to delete this?')" href="{% url 'forums:reply_remove' pk=forum.pk pk1=sub_comment.comment.pk pk2=sub_comment.pk%}">Delete</a>
        {% endif%}
    </p>
</div>
{% endfor %}
{%empty%}
<p>No reply yet.</p>


{% endfor %}


{% endblock%}

thinktank/forums/templates/forums/forum_form.html
{% extends 'thinktank/base.html' %}

{% block title %}Create Forum{% endblock%}

{% block content %}

<h2>Forum</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="btn btn-primary">
</form>

{% endblock %}

thinktank/forums/templates/forums/forum_list.html
{% extends 'thinktank/base.html' %}
{% load static %}
{% block title %}Forums{% endblock%}
{% block link %}
<link rel="stylesheet" href={% static "custom/css/style1.css" %} />
{%endblock%}

{% block content %}
<h4>Forums</h4>
<hr>
{% for forum in forum_list%}
<div class="forum_listshow">
    <div class="answers_count">
        {% with total=forum.comments.count%}
        <p style="text-align:center">{{total}}<br>answer{{total|pluralize}}</p>
        {% endwith%}
    </div>
    <div class="holder">
        <div class="q_n_detail">
            <a href="{% url 'forums:forum_detail' pk=forum.pk%}">{{forum.q_title}}
            </a> <br> <text style="font-size: 14px;">{{forum.detail|truncatewords:30}}</text>
        </div>
        <div class="tags">
            <p><span class="badge badge-primary">{{forum.get_tag_display}}</span></p>
        </div>
        <div class="asker_detail">
            <div class="asked_on">
                <p>asked {{ forum.asked_on}}</p>
            </div>
            <div class="small_holder">
                <div class="user_pic_on_list">
                    {% if forum.questioner.is_student%}
                    {% if forum.questioner.student.profile_picture   %}
                    <img src="{{ forum.questioner.student.profile_picture.url }}" alt="picture" width="50" />
                    {%endif%}
                    {% if not forum.questioner.student.profile_picture %}
                    <img src="/media/icons/person_icon.png" style="background:#ddd;" alt="picture" width="50" />
                    {% endif %}
                    {%endif%}

                    {% if forum.questioner.is_faculty%}
                    {% if  forum.questioner.faculty.profile_picture %}
                    <img src="{{ forum.questioner.faculty.profile_picture.url }}" alt="picture" width="50" />
                    {%endif%}
                    {% if not forum.questioner.faculty.profile_picture %}
                    <img src="/media/icons/person_icon.png" style="background:#ddd;" alt="picture" width="50" />
                    {%endif%}
                    {%endif%}

                </div>
                <div class="user_name_on_list">
                    <p>{{forum.questioner}} <br>
                        {% if forum.questioner.is_student %}
                        <span class="badge badge-secondary">student</span>
                        {% endif %}
                        {% if forum.questioner.is_faculty %}
                        <span class="badge badge-secondary">faculty</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% empty%}
<p>No forums.</p>
{% endfor %}

<div style="float:left; width: 100%; padding:10px;">
    {% if not user.is_authenticated %}
    <a href="{% url 'homepage:index'%}">Login to create forum</a>
    {% endif %}
    {% if user.is_authenticated %}
    <a class="btn btn-success" href="{% url 'forums:create_forum' %}">Create Forum</a>
    {% endif %}
</div>
{% endblock%}